WeWonderGym/WeWonderGym/Controllers/SociosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;
using WeWonderGym.Data;
using WeWonderGym.Models;
using Microsoft.EntityFrameworkCore;
using WeWonderGym.Filters;

namespace WeWonderGym.Controllers
{
    [RoleFilter(Perfil = "Socio")]
    public class SociosController : Controller
    {
        private readonly WeWonderGymDataBaseContext _context;
        private readonly IHostEnvironment _hostEnvironment;

        public SociosController(WeWonderGymDataBaseContext context, IHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        // GET: Socios
        public async Task<IActionResult> Index()
        {
            var weWonderGymDataBaseContext = _context.Socio.Include(s => s.IdUtilizadorNavigation);
            return View(await weWonderGymDataBaseContext.ToListAsync());
        }

        // GET: Socios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var socio = await _context.Socio
                .Include(s => s.IdUtilizadorNavigation)
                .FirstOrDefaultAsync(m => m.IdSocio == id);
            if (socio == null)
            {
                return NotFound();
            }

            return View(socio);
        }

        // GET: Socios/Create
        public IActionResult Create()
        {
            ViewData["IdUtilizador"] = new SelectList(_context.Utilizador, "IdUtilizador", "Email");
            return View();
        }

        // POST: Socios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdUtilizador,IdSocio,Altura")] Socio socio)
        {
            if (ModelState.IsValid)
            {
                _context.Add(socio);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdUtilizador"] = new SelectList(_context.Utilizador, "IdUtilizador", "Email", socio.IdUtilizador);
            return View(socio);
        }

        // GET: Socios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var socio = await _context.Socio.FindAsync(id);
            if (socio == null)
            {
                return NotFound();
            }
            ViewData["IdUtilizador"] = new SelectList(_context.Utilizador, "IdUtilizador", "Email", socio.IdUtilizador);
            return View(socio);
        }

        // POST: Socios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdUtilizador,IdSocio,Altura")] Socio socio)
        {
            if (id != socio.IdSocio)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(socio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SocioExists(socio.IdSocio))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdUtilizador"] = new SelectList(_context.Utilizador, "IdUtilizador", "Email", socio.IdUtilizador);
            return View(socio);
        }

        // GET: Socios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var socio = await _context.Socio
                .Include(s => s.IdUtilizadorNavigation)
                .FirstOrDefaultAsync(m => m.IdSocio == id);
            if (socio == null)
            {
                return NotFound();
            }

            return View(socio);
        }

        // POST: Socios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var socio = await _context.Socio.FindAsync(id);
            _context.Socio.Remove(socio);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SocioExists(int id)
        {
            return _context.Socio.Any(e => e.IdSocio == id);
        }

        //  ################ ZONA AULA DE GRUPO ###############################
        public async Task<IActionResult> IndexAulaGrupo()
        {
            var aulas = _context.Aula.Include(x => x.IdAulaGrupoNavigation).Include(x => x.IdAdminNavigation).Include(x => x.IdProfessorNavigation.IdUtilizadorNavigation);
            Dictionary<int, int> aux = new Dictionary<int, int>();
            int idUtilizador = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
            Socio ss = _context.Socio.First(x => x.IdUtilizador == idUtilizador);

            ViewData["Inscricao"] = dictGeneratorInscricao(ss.IdSocio);
            ViewData["Vagas"] = dictGeneratorVagas();
            return View(await aulas.ToListAsync());
        }

        public async Task<IActionResult> InscreverAula(int id)
        {
            int idUtilizador = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
            Socio ss = _context.Socio.First(x => x.IdUtilizador == idUtilizador);

            Inscrever inscrever = new Inscrever();
            inscrever.IdAula = id;
            inscrever.IdSocio = ss.IdSocio;
            inscrever.IdSocioNavigation = ss;
            inscrever.DataAula = DateTime.Now;

            _context.Inscrever.Add(inscrever);
            await _context.SaveChangesAsync();

            var aulas = _context.Aula.Include(x => x.IdAulaGrupoNavigation).Include(x => x.IdAdminNavigation).Include(x => x.IdProfessorNavigation.IdUtilizadorNavigation);

            ViewData["Inscricao"] = dictGeneratorInscricao(ss.IdSocio);
            ViewData["Vagas"] = dictGeneratorVagas();
            return PartialView("InscreverAulaPartial", aulas);
        }

        public Dictionary<int, int> dictGeneratorInscricao(int idSocio)
        {

            Dictionary<int, int> aux = new Dictionary<int, int>();

            var listaAux = _context.Aula.Select(a =>
                           new SelectListItem
                           {
                               Value = a.IdAula.ToString(),
                               Text = _context.Inscrever.Where(x => x.IdSocio == idSocio && x.IdAula == a.IdAula).ToList().Count.ToString(),
                           }).ToList();
            foreach (var item in listaAux)
            {
                aux[Convert.ToInt32(item.Value)] = Convert.ToInt32(item.Text);
            }

            return aux;
        }
        public Dictionary<int, int> dictGeneratorVagas()
        {

            Dictionary<int, int> aux = new Dictionary<int, int>();

            var listaAux = _context.Aula.Select(a =>
                           new SelectListItem
                           {
                               Value = a.IdAula.ToString(),
                               Text = (a.Lotacao - _context.Inscrever.Where(x => x.IdAula == a.IdAula).ToList().Count).ToString(),
                           }).ToList();

            foreach (var item in listaAux)
            {
                aux[Convert.ToInt32(item.Value)] = Convert.ToInt32(item.Text);
            }

            return aux;
        }

        // ################# PERSONAL TRAINER #####################################
        public IActionResult IndexPersonalTrainer()
        {
            return View();
        }

        public async Task<IActionResult> ListProfessor()
        {
            int idUtilizador = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
            Socio ss = _context.Socio.First(x => x.IdUtilizador == idUtilizador);
            var weWonderGymDataBaseContext = _context.PedidoPt.Include(p => p.IdProfessorNavigation.IdUtilizadorNavigation);
            ViewData["Pedido"] = _context.PedidoPt.Any(x => x.IdSocio == ss.IdSocio && x.Estado != 0);
            ViewData["Professores"] = _context.Professor.Include(x => x.IdUtilizadorNavigation);
            ViewData["IdSocio"] = ss.IdSocio;
            return View(await weWonderGymDataBaseContext.ToListAsync());
        }

        public async Task<IActionResult> RequisitarPT(int id)
        {
            int idUtilizador = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
            Socio ss = _context.Socio.First(x => x.IdUtilizador == idUtilizador);
            PedidoPt pedido = new PedidoPt();

            try
            {
                pedido.DataPedido = DateTime.Now;
                pedido.IdAdmin = 1;
                pedido.IdProfessor = id;
                pedido.IdSocio = ss.IdSocio;
                pedido.Estado = 2;
                _context.PedidoPt.Add(pedido);

                await _context.SaveChangesAsync();
            }catch(Exception e)
            {

WeWonderGym/WeWonderGym/Views/Shared/Erro.cshtml
@{
    ViewData["Title"] = "Erro";
}

<h1>Erro de acesso</h1>

@ViewData["mensagem"]

WeWonderGym/WeWonderGym/Views/Shared/MapaDeAulas.cshtml
@model IEnumerable<WeWonderGym.Models.Aula>
@{
    List<string> helper = new List<string>();
}


<div class="table-wrap col-lg-12">
    <table class="schdule-table table table-bordered">
        <thead class="thead-light">
            <tr>
                <th></th>
                <th class="head" scope="col">Aula</th>
                <th class="head" scope="col">Segunda</th>
                <th class="head" scope="col">Terça</th>
                <th class="head" scope="col">Quarta</th>
                <th class="head" scope="col">Quinta</th>
                <th class="head" scope="col">Sexta</th>
                <th class="head" scope="col">Sabado</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                @if (item.ValidadeDe < DateTime.Now.AddDays(6) && DateTime.Now < item.ValidadeAte)
                {
                    @if (helper.Contains(item.IdAulaGrupoNavigation.Nome) == false)
                    {
                        helper.Add(item.IdAulaGrupoNavigation.Nome);

                        <tr>
                            <th>
                                <img src="~/img/FotosAulas/@item.IdAulaGrupoNavigation.Foto" style="max-height:100px;max-width:100px;" />
                            </th>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdAulaGrupoNavigation.Nome)
                            </td>
                            <td>
                                @foreach (var aula in Model)
                                {
                                    if (aula.IdAulaGrupoNavigation.Nome == item.IdAulaGrupoNavigation.Nome && aula.DiaDaSemana == "Segunda" && aula.ValidadeDe < DateTime.Now.AddDays(6) && DateTime.Now < aula.ValidadeAte)
                                    {
                                        <span>@aula.Hora</span> <br />
                                    }
                                }
                            </td>
                            <td>
                                @foreach (var aula in Model)
                                {
                                    if (aula.IdAulaGrupoNavigation.Nome == item.IdAulaGrupoNavigation.Nome && aula.DiaDaSemana == "Terça"  && aula.ValidadeDe < DateTime.Now.AddDays(6) && DateTime.Now < aula.ValidadeAte)
                                    {
                                        <span>@aula.Hora</span> <br />
                                    }
                                }
                            </td>
                            <td>
                                @foreach (var aula in Model)
                                {
                                    if (aula.IdAulaGrupoNavigation.Nome == item.IdAulaGrupoNavigation.Nome && aula.DiaDaSemana == "Quarta"  && aula.ValidadeDe < DateTime.Now.AddDays(6) && DateTime.Now < aula.ValidadeAte)
                                    {
                                        <span>@aula.Hora</span> <br />
                                    }
                                }
                            </td>
                            <td>
                                @foreach (var aula in Model)
                                {
                                    if (aula.IdAulaGrupoNavigation.Nome == item.IdAulaGrupoNavigation.Nome && aula.DiaDaSemana == "Quinta" && aula.ValidadeDe < DateTime.Now.AddDays(6) && DateTime.Now < aula.ValidadeAte)
                                    {
                                        <span>@aula.Hora</span> <br />
                                    }
                                }
                            </td>
                            <td>
                                @foreach (var aula in Model)
                                {
                                    if (aula.IdAulaGrupoNavigation.Nome == item.IdAulaGrupoNavigation.Nome && aula.DiaDaSemana == "Sexta" && aula.ValidadeDe < DateTime.Now.AddDays(6) && DateTime.Now < aula.ValidadeAte)
                                    {
                                        <span>@aula.Hora</span> <br />
                                    }
                                }
                            </td>
                            <td>
                                @foreach (var aula in Model)
                                {
                                    if (aula.IdAulaGrupoNavigation.Nome == item.IdAulaGrupoNavigation.Nome && aula.DiaDaSemana == "Sabado" && aula.ValidadeDe < DateTime.Now.AddDays(6) && DateTime.Now < aula.ValidadeAte)
                                    {
                                        <span>@aula.Hora</span> <br />
                                    }
                                }
                            </td>
                        </tr>
                    }
                }
            }
        </tbody>
    </table>
</div>

WeWonderGym/WeWonderGym/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using WeWonderGym.Controllers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] WeWonderGym</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="css/linearicons.css">
    <link rel="stylesheet" href="css/owl.carousel.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="css/nice-select.css">
    <link rel="stylesheet" href="css/magnific-popup.css">
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/main.css">
</head>
<body>
    <header id="header">
        <div class="container">

            @if (UtilizadoresController.estaAutenticado(Context))
            {
                <div class="modal" id="sms">

                </div>
                <div class="row header-top align-items-center">
                    <div class="col-lg-4 col-sm-4 menu-top-left">
                        <span>
                            Bem-vindo @Context.Session.GetString("Email")!
                        </span>
                        @if (Context.Session.GetString("Perfil") != "Admin")
                        {
                            <a asp-controller="Utilizadores" asp-action="MenssagemIndex" id="mensagens"
                               data-ajax="true"
                               data-ajax-method="GET"
                               data-ajax-update="#modal"
                               data-ajax-mode="replace">
                                <i class="fa fa-envelope" style="font-size:38px;padding-top:2%;padding-left:10%;align-content:center"></i>
                            </a>
                        }
                    </div>
                    <div class="col-lg-4 menu-top-middle justify-content-center d-flex">
                        <img class="img-fluid" src="~/img/weWonderLogo.png" alt="" style="padding-bottom:15px;">
                    </div>
                    <div class="col-lg-4 col-sm-4 menu-top-right">
                        <a asp-controller="Utilizadores" asp-action="Logout">
                            <span>
                                Logout
                            </span>
                        </a>
                    </div>
                </div>
                if (Context.Session.GetString("Perfil") == "Admin")
                {

                    <div class="container">
                        <div class="row align-items-center justify-content-center d-flex">
                            <nav id="nav-menu-container">
                                <ul class="nav-menu">
                                    <li class="menu-has-children">
                                        <a asp-controller="Administradors" asp-action="IndexProfessor">Professores</a>
                                        <ul>
                                            <li><a asp-controller="Administradors" asp-action="ListProfessor">Lista de Professores</a></li>
                                            <li><a asp-controller="Administradors" asp-action="CreateProf">Adicionar Professor</a></li>
                                            <li><a asp-controller="Administradors" asp-action="ptProfessor">Personal Trainers</a></li>
                                        </ul>
                                    </li>
                                    <li class="menu-has-children">
                                        <a asp-controller="Administradors" asp-action="IndexAulas">Aulas de Grupo</a>
                                        <ul>
                                            <li><a asp-controller="Administradors" asp-action="ListAulas">Lista de Aulas</a></li>
                                            <li><a asp-controller="Administradors" asp-action="CreateAulas">Adicionar Aula</a></li>
                                            <li><a asp-controller="Administradors" asp-action="IndexMapaAulas">Criar Mapa Semanal</a></li>
                                        </ul>
                                    </li>
                                    <li><a asp-controller="Administradors" asp-action="ListSocios">Socios</a></li>
                                    <li><a asp-controller="Administradors" asp-action="ListExercicios">Exercicios</a></li>
                                    <li><a asp-controller="Administradors" asp-action="Index">Administradores</a></li>
                                    <li><a asp-controller="Administradors" asp-action="IndexGinasio">Ginasio</a></li>
                                </ul>
                            </nav><!-- #nav-menu-container -->
                        </div>
                    </div>
                }
                else if (Context.Session.GetString("Perfil") == "Professor")
                {
                    <div class="container">
                        <div class="row align-items-center justify-content-center d-flex">
                            <nav id="nav-menu-container">
                                <ul class="nav-menu">
                                    <li><a asp-controller="Professores" asp-action="IndexAulas">Aulas</a></li>
                                    <li class="menu-has-children">
                                        <a asp-controller="Professores" asp-action="IndexSociosPT">Sócios</a>
                                        <ul>
                                            <li><a asp-controller="Professores" asp-action="ListSociosPT">Sócios Personal Trainer</a></li>
                                            <li><a asp-controller="Professores" asp-action="Pesagem">Pesagem de Sócios</a></li>
                                        </ul>
                                    </li>

                                    <li><a asp-controller="Professores" asp-action="IndexPlanos">Planos</a></li>

                                    <li><a asp-controller="Professores" asp-action="IndexPerfil">Perfil</a></li>
                                </ul>
                            </nav><!-- #nav-menu-container -->
                        </div>
                    </div>
                }
                else
                {
                    <div class="container">
                        <div class="row align-items-center justify-content-center d-flex">
                            <nav id="nav-menu-container">
                                <ul class="nav-menu">
                                    <li><a asp-controller="Socios" asp-action="Historico">Perfil</a></li>
                                    <li><a asp-controller="Socios" asp-action="ListPlano">Plano de Treino</a></li>
                                    <li class="menu-has-children">
                                        <a asp-controller="Socios" asp-action="IndexPersonalTrainer">Personal Trainer</a>
                                        <ul>
                                            <li><a asp-controller="Socios" asp-action="PerfilPT">Personal Trainer Perfil</a></li>
                                            <li><a asp-controller="Socios" asp-action="ListProfessor">Requisitar um Personal Trainer</a></li>
                                        </ul>
                                    </li>
                                    <li><a asp-controller="Socios" asp-action="IndexAulaGrupo">Aulas de Grupo</a></li>
                                </ul>
                            </nav><!-- #nav-menu-container -->
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="row header-top align-items-center">
                    <div class="col-lg-4 col-sm-4 menu-top-left">
                        <span>
                            We believe we help people for happier lives
                        </span>
                    </div>
                    <div class="col-lg-4 menu-top-middle justify-content-center d-flex">
                        <a asp-controller="Home" asp-action="Index">
                            <img class="img-fluid" src="img/weWonderLogo.png" alt="" style="padding-bottom:15px;">
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-4 menu-top-right" id="login">
                        <a class="genric-btn primary e-large" id="login" style="color:#ffffff;font-size:16px;">
                            Login
                        </a>
                    </div>
                    <div class="container">
                        <div class="row align-items-center justify-content-center d-flex">
                            <nav id="nav-menu-container">
                                <ul class="nav-menu">
                                    <li><a href="#offer">Ofertas</a></li>
                                    <li><a href="#top-course">Aulas</a></li>
                                    <li><a href="#schedule">Mapa de Aulas</a></li>
                                    <li><a href="#trainer">Treinadores</a></li>
                                    <li><a href="#aderir">Aderir</a></li>
                                    <li><a href="#contactos">Contactos</a></li>
                                </ul>
                            </nav><!-- #nav-menu-container -->
                        </div>
                    </div>
                </div>
            }
        </div>
    </header><!-- #header -->

    <div class="container" id="corpo">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - WeWonderGym - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="js/vendor/jquery-2.2.4.min.js"></script>
    <script src="js/vendor/bootstrap.min.js"></script>
    <script src="js/easing.min.js"></script>
    <script src="js/hoverIntent.js"></script>
    <script src="js/superfish.min.js"></script>
    <script src="js/jquery.ajaxchimp.min.js"></script>
    <script src="js/jquery.magnific-popup.min.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/jquery.sticky.js"></script>
    <script src="js/jquery.nice-select.min.js"></script>
    <script src="js/parallax.min.js"></script>
    <script src="js/waypoints.min.js"></script>
    <script src="js/jquery.counterup.min.js"></script>
    <script src="js/mail-script.js"></script>
    <script src="js/main.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>