WeWonderGym/WeWonderGym/Controllers/UtilizadoresController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;
using WeWonderGym.Data;
using WeWonderGym.Models;

namespace WeWonderGym.Controllers
{
    public class UtilizadoresController : Controller
    {
        private WeWonderGymDataBaseContext _context;
        private readonly IHostEnvironment _hostEnvironment;

        public UtilizadoresController(WeWonderGymDataBaseContext contextoDB, IHostEnvironment hostEnvironment)
        {
            _context = contextoDB;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Login(string ReturnUrl)
        {
            return PartialView("Login");
        }

        [HttpPost]
        public IActionResult Login(string Email, string Password, string? ReturnUrl, [Bind("Email,Password")] LoginUtilizador utilizador)
        {
            try
            {
                SHA512 sha512 = SHA512Managed.Create();
                byte[] bytes = sha512.ComputeHash(Encoding.UTF8.GetBytes(Password), 0, Encoding.UTF8.GetByteCount(Password));
                string passHash = Convert.ToBase64String(bytes);
                Utilizador uu = _context.Utilizador.SingleOrDefault(u => u.Email == Email);


                if (uu != null)
                {

                    if(uu.Estado == 3)
                    {
                        return RedirectToAction("ConfirmSocio",utilizador);
                    }
                    else if (uu.Estado == 0)
                    {
                        ModelState.AddModelError("Email", _context.Utilizador.FirstOrDefault(x => x.IdUtilizador == uu.IdUtilizador).EstadoMotivo.ToString());
                        return PartialView(utilizador);
                    }

                    Utilizador u = _context.Utilizador.SingleOrDefault(u => u.Email == Email && u.PalavraPass == passHash);
                    if(u != null)
                    {
                        HttpContext.Session.SetString("Email", u.Email);
                        HttpContext.Session.SetInt32("UserId", u.IdUtilizador);

                        if (_context.Socio.FirstOrDefault(x => x.IdUtilizador == u.IdUtilizador) != null)
                        {
                            HttpContext.Session.SetString("Perfil", "Socio");
                            ViewData["Perfil"] = "Socio";
                            ViewData["sucess"] = "true";
                            return PartialView();
                        }

                        if (_context.Professor.FirstOrDefault(x => x.IdUtilizador == u.IdUtilizador) != null)
                        {
                            HttpContext.Session.SetString("Perfil", "Professor");
                            ViewData["Perfil"] = "Professor";
                            ViewData["sucess"] = "true";
                            return PartialView();
                        }
                        else
                        {
                            ModelState.AddModelError("Password","Password Incorreta!");
                            return PartialView(utilizador);
                        }
                    }
                 
                }

                Administrador aa = _context.Administrador.SingleOrDefault(x => x.UserName == Email && x.PalavraPass == passHash);

                if (aa != null)
                {
                    HttpContext.Session.SetString("Email", aa.UserName);
                    HttpContext.Session.SetInt32("UserId", aa.IdAdmin);
                    HttpContext.Session.SetString("Perfil", "Admin"); 
                    ViewData["sucess"] = "true";
                    return PartialView();
                }

                ModelState.AddModelError("Email", "O email não foi encontrado");
                return PartialView(utilizador);

            }
            catch (Exception e)
            {
                ModelState.AddModelError("Email", "Um erro inesperado aconteceu, volte a tentar.");
                return PartialView(utilizador);
            }
        }

        public IActionResult ConfirmSocio(LoginUtilizador u)
        {
          
            return PartialView(u);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmSocio(string email,string pass, string Repass)
        {
            if(pass != Repass)
            {
                ViewBag.Sucesso = "erro";
                LoginUtilizador u = new LoginUtilizador();
                u.Email = email;
                return PartialView(u);
            }

            SHA512 sha512 = SHA512Managed.Create();
            byte[] bytes = sha512.ComputeHash(Encoding.UTF8.GetBytes(pass), 0, Encoding.UTF8.GetByteCount(pass));
            string passHash = Convert.ToBase64String(bytes);


            var util = _context.Utilizador.SingleOrDefault(x => x.Email == email);
            util.PalavraPass = passHash;
            util.Estado = 1;
            _context.Utilizador.Update(util);
            _context.SaveChanges();

            return RedirectToAction("Login");
        }

        public IActionResult Logout()
        {
            HttpContext.Response.Cookies.Delete("CookieSessao");
            return LocalRedirect("/");
        }

        public static bool isSocio(HttpContext contexto)
        {
            if (contexto.Session.GetString("Perfil") == "Socio")
                return true;
            else
                return false;
        }

        public static bool isProfessor(HttpContext contexto)
        {
            if (contexto.Session.GetString("Perfil") == "Professor")
                return true;
            else
                return false;
        }

        public static bool isAdmin(HttpContext contexto)
        {
            if (contexto.Session.GetString("Perfil") == "Admin")
                return true;
            else
                return false;
        }

        public static bool estaAutenticado(HttpContext contexto)
        {
            if (contexto.Session.GetInt32("UserId") != null)
                return true;
            else
                return false;
        }


        // GET: Utilizadors
        public async Task<IActionResult> Index()
        {
            var weWonderGymDataBaseContext = _context.Utilizador.Include(u => u.IdAdminNavigation);
            return View(await weWonderGymDataBaseContext.ToListAsync());
        }

        // GET: Utilizadors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var utilizador = await _context.Utilizador
                .Include(u => u.IdAdminNavigation)
                .FirstOrDefaultAsync(m => m.IdUtilizador == id);
            if (utilizador == null)
            {
                return NotFound();
            }

            return View(utilizador);
        }

        // GET: Utilizadors/Create
        public IActionResult Create()
        {
            return PartialView("Create");
        }

        // POST: Utilizadors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormCollection colletion, [Bind("IdUtilizador,IdAdmin,NumTelefone,Nome,Fotografica,Estado,Sexo,Email,PalavraPass")] Utilizador utilizador)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    utilizador.PalavraPass = RandomString(7);
                    SHA512 sha512 = SHA512Managed.Create();
                    byte[] bytes = sha512.ComputeHash(Encoding.UTF8.GetBytes(utilizador.PalavraPass), 0, Encoding.UTF8.GetByteCount(utilizador.PalavraPass));
                    string passHash = Convert.ToBase64String(bytes);
                    utilizador.PalavraPass = passHash;
                    utilizador.Estado = 2;
                    utilizador.IdAdmin = 1;
                    utilizador.EstadoMotivo = "A sua conta ainda não foi ativada!";

                    IFormFile file = colletion.Files.First();
                    string caminho = Path.Combine(_hostEnvironment.ContentRootPath, "wwwroot\\img\\Fotos\\Utilizador");
                    string nome_ficheiro = Path.GetFileName(file.FileName);
                    string caminho_completo = Path.Combine(caminho, nome_ficheiro);
                    FileStream fs = new FileStream(caminho_completo, FileMode.Create);
                    file.CopyTo(fs);
                    fs.Close();

                    utilizador.Fotografica = nome_ficheiro;
                    _context.Add(utilizador);
                    await _context.SaveChangesAsync();

                    var ss = new Socio();
                    ss.Altura = colletion["Altura"];
                    Utilizador utl = _context.Utilizador.First(x => x.Email == utilizador.Email);
                    ss.IdUtilizador = utl.IdUtilizador;
                    ss.IdSocio = utl.IdUtilizador + 2;
                    _context.Add(ss);
                    await _context.SaveChangesAsync();
                    ViewData["Sucess"] = "sucesso";
                    return PartialView();
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("Email", "Email já em uso!");
                    return PartialView(utilizador);
                }

            }
            ViewData["IdAdmin"] = new SelectList(_context.Administrador, "IdAdmin", "Username", utilizador.IdAdmin);

WeWonderGym/WeWonderGym/Views/Utilizadores/ConfirmSocio.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model WeWonderGym.Models.LoginUtilizador

<div class="modal-dialog" style="padding-top:15%;">
    <div class="modal-content" style="max-width:300px;left:20%">
        <h4>Redefinição da Password</h4>
        <form asp-action="ConfirmSocio" asp-controller="Utilizadores"
              data-ajax="true"
              data-ajax-method="POST"
              data-ajax-update="#modal"
              data-ajax-mode="replace"
              data-ajax-sucess="sucesso">
            <input name="email" value="@Model.Email" type="hidden" />
            <div class="form-group">
                <label class="control-label">Nova Password</label>
                <input class="form-control" type="password" name="pass" id="pass" required />
                <span class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Repetir Password</label>
                <input class="form-control" type="password" name="Repass" id="Repass" required />
                <span class="text-danger"></span>
            </div>
            @if (ViewBag.Sucesso == "erro")
            {
                <span style="color:#ff0000;font-size:14px;align-content:center;">As Passwords não coincidem, por favor tente outra vez.</span>
            }
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div><!-- /.modal-dialog -->

WeWonderGym/WeWonderGym/Views/Utilizadores/Create.cshtml
@model WeWonderGym.Models.Utilizador
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="modal-dialog" style="padding-top:15%;"id="box">
    <div class="modal-content" style="padding-top:2%;padding-bottom:2%;padding-left:2%;padding-right:2%;">
         @if(ViewBag.Sucess == "sucesso"){
             <span style="color:#148b3e;font-size:14px;align-content:center;"> O seu pedido foi enviado com sucesso!</span>
         }
        <form asp-action="Create" enctype="multipart/form-data"
              data-ajax="true"
              data-ajax-method="POST"
              data-ajax-update="#box"
              data-ajax-mode="replace">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NumTelefone" class="control-label"></label>
                <input asp-for="NumTelefone" class="form-control" required />
                <span asp-validation-for="NumTelefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" required />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fotografica" class="control-label"></label>
                <input asp-for="Fotografica" type="file" accept="image/*" class="form-control" required />
                <span asp-validation-for="Fotografica" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <select asp-for="Sexo" class="form-control">
                    <option value="Masculino">Masculino</option>
                    <option value="Feminino">Feminino</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" required />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="PalavraPass" type="hidden" class="form-control" required />
            </div>
            <div class="form-group">
                <label class="control-label"> Altura</label>
                <input name="Altura" class="form-control" required />
                <span  class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submeter" class="genric-btn primary circle arrow" />
            </div>
        </form>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

WeWonderGym/WeWonderGym/Views/Utilizadores/ForgotPass.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<div class="modal-dialog" style="padding-top:15%;">
    <div class="modal-content" style="max-width:300px;left:20%">
        <form asp-action="ForgotPass" asp-controller="Utilizadores"
              data-ajax="true"
              data-ajax-method="POST"
              data-ajax-update="#modal"
              data-ajax-mode="replace">
            <div class="form-group">
                <label class="control-label">Email</label>
                <input class="form-control" type="email" name="email" id="email" />
                <span class="text-danger"></span>
            </div>
            @if (ViewBag.Sucesso == "erro")
            {
                <span style="color:#ff0000;font-size:14px;align-content:center;">O email inserido não se encontra registado, verifique e tente novamente.</span>
            }
            <div class="form-group">
                <input type="submit" value="Enviar Email" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div><!-- /.modal-dialog -->

WeWonderGym/WeWonderGym/Views/Utilizadores/Login.cshtml
@model WeWonderGym.Models.LoginUtilizador
@{
    Layout = null;
}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body {
            background-color: #808080;
        }

        * {
            box-sizing: border-box;
        }


        /* Add styles to the form container */
        .form-container {
            max-width: 300px;
            padding: 10px;
            background-color: white;
        }

            /* Full-width input fields */
            .form-container input[type=text], .form-container input[type=password] {
                width: 100%;
                padding: 15px;
                margin: 5px 0 22px 0;
                border: none;
                background: #f1f1f1;
            }

                /* When the inputs get focus, do something */
                .form-container input[type=text]:focus, .form-container input[type=password]:focus {
                    background-color: #ddd;
                    outline: none;
                }

            /* Set a style for the submit/login button */
            .form-container .btn {
                background-color: #4CAF50;
                color: white;
                padding: 16px 20px;
                border: none;
                cursor: pointer;
                width: 100%;
                margin-bottom: 10px;
                opacity: 0.8;
            }

            /* Add a red background color to the cancel button */
            .form-container .cancel {
                background-color: red;
            }

            /* Add some hover effects to buttons */
            .form-container .btn:hover, .open-button:hover {
                opacity: 1;
            }
    </style>

    <link rel="stylesheet" href="~/css/bootstrap.css">
</head>


<div class="modal-dialog" style="padding-top:15%;" id="box">
    <div class="modal-content" style="max-width:300px;left:20%">
        <form asp-action="Login" method="post" class="form-container"
              data-ajax="true"
              data-ajax-method="POST"
              data-ajax-update="#box"
              data-ajax-mode="replace"
              data-ajax-sucess="sucesso">
            <h1>Login</h1>
            <div asp-validation-summary="ModelOnly" class="text-danger" data-valmsg-summary="true"></div>
            <div class="form-group">
                <label class="control-label">Email</label>
                <input type="text" name="Email" placeholder="Insira o Email" required />.
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Password</label>
                <input type="password" name="Password" placeholder="Insira a password" required />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Entrar" class="btn btn-primary" />
                <button type="button" value="Close" class="btn cancel" data-dismiss="modal">Fechar</button>
            </div>
        </form>
        <a class="btn btn-primary forgot" style="color:#ffffff" id="forgot">Esqueceu-se da Password?</a>
    </div>
</div><!-- /.modal-dialog -->

<script>
    $(document).ready(
        function sucesso() {
            @if(ViewBag.sucess == "true")
            {
                if(ViewBag.Perfil == "Socio")
                {
                     @:window.location.href = "/Socios/Historico"

                }else if(ViewBag.Perfil == "Professor")
                {
                    @:window.location.href="/Professores/IndexPerfil"
                }
                else
                {
                   @:window.location.href="/Administradors/IndexGinasio"
                }

            }

        }
    );

</script>
<script>
    $(function () {
        $(".forgot").click(function () {
            $("#modal").load("Utilizadores/ForgotPass", function () {
                $("#modal").modal();
            })
        });
    })
</script>

WeWonderGym/WeWonderGym/Views/Utilizadores/LoginSucess.cshtml
<div class="modal-dialog" style="padding-top:15%;" id="box">
    <div class="modal-content" style="padding-top:2%;padding-bottom:2%;padding-left:2%;padding-right:2%;">
        <h3>Seja muito bem bem-vindo!</h3>
        <button></button>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

WeWonderGym/WeWonderGym/Views/Utilizadores/MenssagemIndex.cshtml
@model IEnumerable<WeWonderGym.Models.Mensagem>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    string assunto = "";
}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body {
            font-family: Arial;
        }

        /* Style the tab */
        .tab {
            overflow: hidden;
            border: 1px solid #ccc;
            background-color: #f1f1f1;
        }

            /* Style the buttons inside the tab */
            .tab button {
                background-color: inherit;
                float: left;
                border: none;
                outline: none;
                cursor: pointer;
                padding: 14px 16px;
                transition: 0.3s;
                font-size: 17px;
            }

                /* Change background color of buttons on hover */
                .tab button:hover {
                    background-color: #ddd;
                }

                /* Create an active/current tablink class */
                .tab button.active {
                    background-color: #ccc;
                }

        /* Style the tab content */
        .tabcontent {
            display: none;
            padding: 6px 12px;
            border: 1px solid #ccc;
            border-top: none;
        }
    </style>
</head>

<div class="modal-dialog" style="padding-top:15%;" id="caixa">
    <div class="modal-content" style="width:630px">
        <div class="tab">
            <button class="tablinks" onclick="openCity(event, 'Recebidas')">Recebidas</button>
            <button class="tablinks" onclick="openCity(event, 'Enviadas')">Enviadas</button>
            <button class="tablinks" onclick="openCity(event, 'Mensagem')">Nova Mensagem</button>
            <button class="tablinks" onclick="openCity(event, 'Arquivadas')">Arquivadas</button>
        </div>

        <!-- Tab content -->
        <div id="Recebidas" class="tabcontent">
            <table class="schdule-table table table-bordered">
                <thead class="thead-light">
                    <tr>
                        <th class="head" scope="col">De</th>
                        <th class="head" scope="col">Recebida a</th>
                        <th class="head" scope="col">Assunto</th>
                        <th class="head" scope="col">Estado</th>
                        <th class="head" scope="col">Opções</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        @if (ViewBag.UserEmail == item.UtilizadorParaNavigation.Email && !item.Arquivada)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UtilizadorDeNavigation.Email)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DataRecebido)
                                </td>
                                <td>
                                    <a asp-action="ShowMensagemPartial" asp-controller="Utilizadores" asp-route-id="@item.IdMensagem"
                                       data-ajax="true"
                                       data-ajax-method="GET"
                                       data-ajax-update="#caixa"
                                       data-ajax-mode="replace"
                                       data-ajax-sucess="sucesso">
                                        @(assunto = item.Texto.ToString().Substring(0, 3))
                                    </a>
                                </td>
                                <td>
                                    @if (item.Lida == false)
                                    {
                                        <span>Não lida</span>
                                    }
                                    else
                                    {
                                        <span>Lida</span>
                                    }
                                </td>
                                <td>
                                    <a asp-action="ArquivarMensagem" asp-controller="Utilizadores" asp-route-id="@item.IdMensagem"
                                       data-ajax="true"
                                       data-ajax-method="GET"
                                       data-ajax-update="#caixa"
                                       data-ajax-mode="replace"
                                       data-ajax-sucess="sucesso">
                                        Arquivar
                                    </a>
                                </td>
                            </tr>
                        }

                    }
                </tbody>
            </table>
        </div>

        <div id="Enviadas" class="tabcontent">
            <table class="schdule-table table table-bordered">
                <thead class="thead-light">
                    <tr>
                        <th class="head" scope="col">Para</th>
                        <th class="head" scope="col">Enviada a</th>
                        <th class="head" scope="col">Assunto</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        @if (ViewBag.UserEmail == item.UtilizadorDeNavigation.Email)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UtilizadorParaNavigation.Email)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DataRecebido)
                                </td>
                                <td>
                                    <a asp-action="ShowMensagemPartial" asp-controller="Utilizadores" asp-route-id="@item.IdMensagem"
                                       data-ajax="true"
                                       data-ajax-method="POST"
                                       data-ajax-update="#caixa"
                                       data-ajax-mode="replace"
                                       data-ajax-sucess="sucesso">
                                        @(assunto = item.Texto.ToString().Substring(0, 3))
                                    </a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>

        <div id="Mensagem" class="tabcontent">
            <form asp-action="EnviarMensagem" asp-controller="Utilizadores"
                  data-ajax="true"
                  data-ajax-method="POST"
                  data-ajax-update="#caixa"
                  data-ajax-mode="replace"
                  data-ajax-sucess="sucesso">
                @if (ViewBag.sucess == "yes")
                {
                    <span style="color:#148b3e;font-size:14px;align-content:center;"> A sua mensagem foi enviada com sucesso!</span>
                }
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label class="control-label">Para:</label>
                    <select name="UtilizadorPara" class="form-control" asp-items="ViewBag.UtilizadorPara"></select>
                </div>
                <div class="form-group">
                    <label class="control-label">Texto</label>
                    <textarea name="Texto" class="form-text" style="height:250px;width:565px;" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Enviar" class="genric-btn primary circle arrow" />
                </div>
            </form>
        </div>

        <div id="Arquivadas" class="tabcontent">
            <table class="schdule-table table table-bordered">
                <thead class="thead-light">
                    <tr>
                        <th class="head" scope="col">De</th>
                        <th class="head" scope="col">Recebida a</th>
                        <th class="head" scope="col">Assunto</th>
                        <th class="head" scope="col">Estado</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        @if (item.Arquivada && ViewBag.UserEmail == item.UtilizadorParaNavigation.Email)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UtilizadorDeNavigation.Email)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DataRecebido)
                                </td>
                                <td>
                                    <a asp-action="ShowMensagemPartial" asp-controller="Utilizadores" asp-route-id="@item.IdMensagem"
                                       data-ajax="true"
                                       data-ajax-method="POST"
                                       data-ajax-update="#caixa"
                                       data-ajax-mode="replace"
                                       data-ajax-sucess="sucesso">
                                        @(assunto = item.Texto.ToString().Substring(0, 3))
                                    </a>
                                </td>
                                <td>

                                    @if (item.Lida == false)
                                    {
                                        <span>Não lida</span>
                                    }
                                    else
                                    {
                                        <span>Lida</span>
                                    }

                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    function openCity(evt, cityName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(cityName).style.display = "block";
        evt.currentTarget.className += " active";
    }
</script>
</div><!-- /.modal-dialog -->