WeWonderGym/WeWonderGym/Models/Administrador.cs
using System;
using System.Collections.Generic;

namespace WeWonderGym.Models
{
    public partial class Administrador
    {
        public Administrador()
        {
            Aula = new HashSet<Aula>();
            AulaGrupo = new HashSet<AulaGrupo>();
            ExercicioGinasio = new HashSet<ExercicioGinasio>();
            PedidoPt = new HashSet<PedidoPt>();
            Utilizador = new HashSet<Utilizador>();
        }

        public int IdAdmin { get; set; }
        public string UserName { get; set; }
        public string PalavraPass { get; set; }

        public virtual ICollection<Aula> Aula { get; set; }
        public virtual ICollection<AulaGrupo> AulaGrupo { get; set; }
        public virtual ICollection<ExercicioGinasio> ExercicioGinasio { get; set; }
        public virtual ICollection<PedidoPt> PedidoPt { get; set; }
        public virtual ICollection<Utilizador> Utilizador { get; set; }
    }
}

WeWonderGym/WeWonderGym/Controllers/AdministradorsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using WeWonderGym.Data;
using WeWonderGym.Filters;
using WeWonderGym.Models;

namespace WeWonderGym.Controllers
{
    [RoleFilter(Perfil = "Admin")]
    public class AdministradorsController : Controller
    {
        private readonly WeWonderGymDataBaseContext _context;
        private readonly IHostEnvironment _hostEnvironment;

        public AdministradorsController(WeWonderGymDataBaseContext context, IHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        // GET: Administradors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Administrador.ToListAsync());
        }

        // GET: Administradors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var administrador = await _context.Administrador
                .FirstOrDefaultAsync(m => m.IdAdmin == id);
            if (administrador == null)
            {
                return NotFound();
            }

            return View(administrador);
        }

        // GET: Administradors/Create
        public IActionResult Create()
        {
            return PartialView();
        }

        // POST: Administradors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdAdmin,UserName,PalavraPass")] Administrador administrador)
        {
            if (ModelState.IsValid)
            {
                SHA512 sha512 = SHA512Managed.Create();
                byte[] bytes = sha512.ComputeHash(Encoding.UTF8.GetBytes(administrador.PalavraPass), 0, Encoding.UTF8.GetByteCount(administrador.PalavraPass));
                string passHash = Convert.ToBase64String(bytes);
                administrador.PalavraPass = passHash;
                _context.Add(administrador);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(administrador);
        }

        // GET: Administradors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var administrador = await _context.Administrador.FindAsync(id);
            if (administrador == null)
            {
                return NotFound();
            }
            return View(administrador);
        }

        // POST: Administradors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdAdmin,UserName,PalavraPass")] Administrador administrador)
        {
            if (id != administrador.IdAdmin)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(administrador);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdministradorExists(administrador.IdAdmin))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(administrador);
        }

        // GET: Administradors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var administrador = await _context.Administrador
                .FirstOrDefaultAsync(m => m.IdAdmin == id);
            if (administrador == null)
            {
                return NotFound();
            }

            return View(administrador);
        }

        // POST: Administradors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var administrador = await _context.Administrador.FindAsync(id);
            _context.Administrador.Remove(administrador);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AdministradorExists(int id)
        {
            return _context.Administrador.Any(e => e.IdAdmin == id);
        }


        // ############### ZONA Professor ##########################
        public IActionResult CreateProf()
        {
            ViewData["IdAdmin"] = new SelectList(_context.Administrador, "IdAdmin", "PalavraPass");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateProf(IFormCollection colletion, [Bind("IdUtilizador,IdAdmin,NumTelefone,Nome,Fotografica,Estado,Sexo,Email,PalavraPass,IdUtilizador, IdProfessor, Especialidade")] Utilizador utilizador)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    SHA512 sha512 = SHA512Managed.Create();
                    byte[] bytes = sha512.ComputeHash(Encoding.UTF8.GetBytes(utilizador.PalavraPass), 0, Encoding.UTF8.GetByteCount(utilizador.PalavraPass));
                    string passHash = Convert.ToBase64String(bytes);
                    utilizador.PalavraPass = passHash;
                    utilizador.Estado = 1;
                    utilizador.EstadoMotivo = "Professor Ativo";
                    utilizador.IdAdmin = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));


                    IFormFile file = colletion.Files.First();
                    string caminho = Path.Combine(_hostEnvironment.ContentRootPath, "wwwroot\\img\\Fotos");
                    string nome_ficheiro = Path.GetFileName(file.FileName);
                    string caminho_completo = Path.Combine(caminho, nome_ficheiro);
                    FileStream fs = new FileStream(caminho_completo, FileMode.Create);
                    file.CopyTo(fs);
                    fs.Close();

                    utilizador.Fotografica = nome_ficheiro;
                    _context.Add(utilizador);
                    await _context.SaveChangesAsync();

                    var utl = _context.Utilizador.FirstOrDefault(x => x.Email == utilizador.Email);
                    utilizador.Professor = new Professor { Especialidade = colletion["Especialidade"], IdProfessor = utl.IdUtilizador + 2 };

                    _context.Update(utilizador);
                    await _context.SaveChangesAsync();


                    return RedirectToAction("ListProfessor");
                }
            }catch(Exception e)
            {
                ViewData["emailRepetido"] = "true";
                return View();
            }
    
            ViewData["IdAdmin"] = new SelectList(_context.Administrador, "IdAdmin", "Username", utilizador.IdAdmin);
            return Redirect("ListProfessor");
        }

        public IActionResult IndexProfessor()
        {
            return View();
        }

        public async Task<IActionResult> ListProfessor()
        {
            var weWonderGymDataBaseContext = _context.Professor.Include(p => p.IdUtilizadorNavigation);
            return View(await weWonderGymDataBaseContext.ToListAsync());
        }

        public IActionResult EditProfessor(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var professor = _context.Professor.Include(p => p.IdUtilizadorNavigation).SingleOrDefault(p => p.IdProfessor == id);
            if (professor == null)
            {
                return NotFound();
            }
            ViewData["IdUtilizador"] = new SelectList(_context.Utilizador, "IdUtilizador", "Email", professor.IdUtilizador);
            return PartialView(professor);
        }

        // POST: Professors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditProfessor(int id, IFormCollection collection, [Bind("IdUtilizador,IdProfessor,Especialidade,Estado")] Professor professor)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    var utl = _context.Utilizador.FirstOrDefault(x => x.IdUtilizador == professor.IdUtilizador);
                    if (utl != null)
                    {
                        utl.Estado = Convert.ToInt32(collection["Estado"]);
                        _context.Utilizador.Update(utl);
                        await _context.SaveChangesAsync();
                    }
                    _context.Update(professor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

WeWonderGym/WeWonderGym/Views/Administradors/AlterarUtlEstado.cshtml
@model WeWonderGym.Models.Utilizador

@{
    Layout = null;
    ViewBag.Title = "Details";
}
<head>
    <link rel="stylesheet" href="~/css/bootstrap.css">
</head>
<body>
    <div class="modal-dialog" style="padding-top:15%;">
        <div class="modal-content" style="padding-top:2%;padding-bottom:2%;padding-left:2%;padding-right:2%;">
            <form asp-action="AlterarUtlEstado" asp-controller="Administradors" 
                  data-ajax="true"
                  data-ajax-method="POST"
                  data-ajax-mode="replace"
                  data-ajax-update="#tabela">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="IdUtilizador" value="@Model.IdUtilizador" />

                <div class="form-group">
                    <label asp-for="EstadoMotivo" class="control-label"></label>
                    <input asp-for="EstadoMotivo" class="form-control" />
                    <span asp-validation-for="EstadoMotivo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Estado</label>
                    <select name="Estado" class="form-control">
                        <option value="1">Ativo</option>
                        <option value="0">Inativo</option>
                    </select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary"/>
                    <input type="button" value="Fechar" class="btn btn-default" data-dismiss="modal" />
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</body>

WeWonderGym/WeWonderGym/Views/Administradors/CreateProf.cshtml
@model WeWonderGym.Models.Utilizador

@{
    ViewData["Title"] = "Create";
}

<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="~/img/elements/fav.png">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Adicionar Professor</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="/stylesheet" href="~/css/linearicons.css">
    <link rel="stylesheet" href="~/css/owl.carousel.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/nice-select.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/main.css">
</head>
<body>
    <div class="main-wrapper">

        <!-- Start offer Area -->
        <section class="offer-area pt-100" id="offer">
            <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="menu-content pb-70 col-lg-8">
                        <div class="title text-center">
                            <h1 id="listaProf"></h1>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <a asp-controller="Administradors" asp-action="ListProfessor">
                            <div class="single-offer">
                                <img class="img-fluid" src="~/img/o1.png" alt="">
                                <h4>Lista de Professores</h4>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4">
                        <a asp-controller="Administradors" asp-action="CreateProf">
                            <div class="single-offer">
                                <img class="img-fluid" src="~/img/o2.png" alt="">
                                <h4>Adicionar Professor</h4>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4">
                        <a asp-controller="Administradors" asp-action="ptProfessor">
                            <div class="single-offer">
                                <img class="img-fluid" src="~/img/o3.png" alt="">
                                <h4>Personal Trainers</h4>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </section>
        <!-- End offer Area -->
        <!-- Start Generic Area -->
        <section class="about-generic-area section-gap">
            <div style="padding-left:15%;padding-right:15%;">
                <form asp-action="CreateProf" enctype="multipart/form-data">
                    @if (ViewBag.emailRepetido == "true")
                    {
                        <h4 style="color:red"> Erro: Email em uso!</h4>
                    }

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nome" class="control-label"></label>
                        <input asp-for="Nome" class="form-control" required />
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Fotografica" class="control-label"></label>
                        <input asp-for="Fotografica" type="file" accept="image/*" class="form-control" required />
                        <span asp-validation-for="Fotografica" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Sexo" class="control-label"></label>
                        <select asp-for="Sexo" class="form-control">
                            <option value="Masculino">Masculino</option>
                            <option value="Feminino">Feminino</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="NumTelefone" class="control-label"></label>
                        <input asp-for="NumTelefone" class="form-control" required />
                        <span asp-validation-for="NumTelefone" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" required />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PalavraPass" class="control-label"></label>
                        <input asp-for="PalavraPass" class="form-control" type="password" required />
                        <span asp-validation-for="PalavraPass" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Especialidade</label>
                        <input class="form-control" name="Especialidade" required />
                        <span class="text-danger"></span>
                    </div>
                    <div>
                        <input type="submit" value=" Adicionar" class="genric-btn primary circle arrow" />
                    </div>
                </form>
            </div>
        </section>
    </div>

    <div class="modal" id="modal">
    </div>
    <!-- End Generic Start -->
    <script src="~/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="~/js/vendor/bootstrap.min.js"></script>
    <script src="~/js/easing.min.js"></script>
    <script src="~/js/hoverIntent.js"></script>
    <script src="~/js/superfish.min.js"></script>
    <script src="~/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.sticky.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/jquery.counterup.min.js"></script>
    <script src="~/js/main.js"></script>
</body>
</html>

<script>
    $(function () {
        $("#mensagens").click(function () {
            $("#modal").load("Utilizadores/MenssagensIndex", function () {
                $("#modal").modal();
            })
        });
    })
</script>

WeWonderGym/WeWonderGym/Views/Administradors/EditAula.cshtml
@model WeWonderGym.Models.AulaGrupo

@{
    Layout = null;
    ViewBag.Title = "Details";
}
<head>
    <link rel="stylesheet" href="~/css/bootstrap.css">
</head>
<body>
    <div class="modal-dialog" style="padding-top:15%;">
        <div class="modal-content" style="padding-top:2%;padding-bottom:2%;padding-left:2%;padding-right:2%;">
            <form asp-action="EditAula" asp-controller="Administradors" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="IdAdmin" />
                <input type="hidden" asp-for="IdAulaGrupo" />

                <div class="form-group">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Foto" class="control-label"></label>
                    <input asp-for="Foto" type="file" accept="image/*" value="@Model.Foto" class="form-control" />
                    <span asp-validation-for="Foto" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Descricao" class="control-label"></label>
                    <input asp-for="Descricao" class="form-control" />
                    <span asp-validation-for="Descricao" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Guardar" class="btn btn-primary" />
                    <input type="button" value="Cancelar" class="btn btn-default" data-dismiss="modal" />
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</body>

WeWonderGym/WeWonderGym/Views/Administradors/EditProfessor.cshtml
@model WeWonderGym.Models.Professor

@{
    Layout = null;
    ViewBag.Title = "Details";
}
    <head>
        <link rel="stylesheet" href="~/css/bootstrap.css">
    </head>
    <body>
        <div class="modal-dialog" style="padding-top:15%;">
            <div class="modal-content" style="padding-top:2%;padding-bottom:2%;padding-left:2%;padding-right:2%;">
                <form asp-action="EditProfessor" asp-controller="Administradors" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="IdUtilizador" value="@Model.IdUtilizador"/>
                    <input type="hidden" asp-for="IdProfessor" value="@Model.IdProfessor" />

                    <div class="form-group">
                        <label asp-for="Especialidade" class="control-label"></label>
                        <input asp-for="Especialidade" class="form-control" />
                        <span asp-validation-for="Especialidade" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Estado</label>
                        <select name="Estado" class="form-control">
                            <option value="1">Ativo</option>
                            <option value="0">Inativo</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                        <input type="button" value="Cancelar" class="btn btn-default" data-dismiss="modal" />
                    </div>
                </form>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </body>

WeWonderGym/WeWonderGym/Views/Administradors/IndexAulas.cshtml
@{
    ViewData["Title"] = "Aulas";
}

<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="~/img/elements/fav.png">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Ginasio</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="/stylesheet" href="~/css/linearicons.css">
    <link rel="stylesheet" href="~/css/owl.carousel.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/nice-select.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/main.css">
</head>
<body>
    <section class="banner-aulas relative" id="home" style="max-height:500px;">
        <div class="container">
            <div class="row fullscreen d-flex align-items-start justify-content-start" style="padding-top:12.5%; max-height:500px;">
                <div class="banner-content col-lg-12 col-md-12">
                    <h1 class="text-white">Aulas de Grupo</h1>
                    <p class="text-white">Aqui pode gerir as aulas de grupo do ginasio  é possivel criar novas aulas, <br> editar as existentes e fazer o mapa de aulas semana .</p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->
    <!-- About Generic Start -->
    <div class="main-wrapper">
        <!-- Start offer Area -->
        <section class="offer-area pt-100" id="offer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <a asp-controller="Administradors" asp-action="ListAulas">
                            <div class="single-offer">
                                <img class="img-fluid" src="~/img/o1.png" alt="">
                                <h4>Lista de Aulas</h4>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4">
                        <a asp-controller="Administradors" asp-action="CreateAulas">
                            <div class="single-offer">
                                <img class="img-fluid" src="~/img/o2.png" alt="">
                                <h4>Adicionar Aula</h4>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4">
                        <a asp-controller="Administradors" asp-action="IndexMapaAulas">
                            <div class="single-offer">
                                <img class="img-fluid" src="~/img/o3.png" alt="">
                                <h4>Criar mapa semanal</h4>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <div class="modal" id="modal">
    </div>

    <!-- End offer Area -->
    <!-- Start Generic Area -->
    <section class="about-generic-area section-gap">
    </section>

    <script src="~/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="~/js/vendor/bootstrap.min.js"></script>
    <script src="~/js/easing.min.js"></script>
    <script src="~/js/hoverIntent.js"></script>
    <script src="~/js/superfish.min.js"></script>
    <script src="~/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.sticky.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/jquery.counterup.min.js"></script>
    <script src="~/js/main.js"></script>
</body>

<script>
    $(function () {
        $("#mensagens").click(function () {
            $("#modal").load("Utilizadores/MenssagensIndex", function () {
                $("#modal").modal();
            })
        });
    })
</script>

WeWonderGym/WeWonderGym/Views/Administradors/ListExerciciosPartial.cshtml
@model IEnumerable<WeWonderGym.Models.ExercicioGinasio>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="table-wrap col-lg-12" id="tabela">
    <table class="schdule-table table table-bordered">
        <thead class="thead-light">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Foto)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Descricao)
                </th>
                <th>
                    Criado Por
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Video)
                </th>
                <th>
                    Opções
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <img src="~/img/imgExercicios/Fotos/@item.Foto" style="max-height:100px;max-width:100px;" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descricao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdAdminNavigation.UserName)
                    </td>
                    <td>
                        <video width="320" height="240"style="max-height:150px;max-width:150px;"  controls>
                            <source src="~/img/imgExercicios/Video/@item.Video" type="video/mp4">
                            Your browser does not support the video tag.
                        </video>
                    </td>
                    <td>
                        <a asp-controller="Administradors" asp-action="DeleteExercio" asp-route-id="@item.IdExercicio"
                           data-ajax="true"
                           data-ajax-method="GET"
                           data-ajax-mode="replace"
                           data-ajax-update="#tabela"
                           data-ajax-confirm="Tem a certeza que quer apagar este exercicio?">Apagar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>