WeWonderGym/WeWonderGym/Controllers/ProfessoresController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;
using WeWonderGym.Data;
using WeWonderGym.Models;
using Microsoft.EntityFrameworkCore;
using WeWonderGym.Filters;

namespace WeWonderGym.Controllers
{
    [RoleFilter(Perfil = "Professor")]
    public class ProfessoresController : Controller
    {
        private readonly WeWonderGymDataBaseContext _context;
        private readonly IHostEnvironment _hostEnvironment;

        public ProfessoresController(WeWonderGymDataBaseContext context, IHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }
        public ActionResult Index()
        {
            return View();
        }

        //#############Perfil###################
        public ActionResult IndexPerfil()
        {
            var utilizador = _context.Utilizador.FirstOrDefault(x => x.IdUtilizador == Convert.ToInt32(HttpContext.Session.GetInt32("UserId")));
            return View(utilizador);
        }


        [HttpPost]
        public async Task<IActionResult> IndexPerfil(IFormCollection colletion, [Bind("NumTelefone,Fotografica,PalavraPass")] Utilizador utilizador, string OldPass)
        {
            Utilizador edit = _context.Utilizador.Find(Convert.ToInt32(HttpContext.Session.GetInt32("UserId")));
            SHA512 sha512 = SHA512Managed.Create();
            if (utilizador.PalavraPass != null)
            {
                byte[] bytes = sha512.ComputeHash(Encoding.UTF8.GetBytes(utilizador.PalavraPass), 0, Encoding.UTF8.GetByteCount(utilizador.PalavraPass));
                string passHash = Convert.ToBase64String(bytes);
                utilizador.PalavraPass = passHash;
            }
            if (OldPass != null)
            {
                byte[] bytesOldPass = sha512.ComputeHash(Encoding.UTF8.GetBytes(OldPass), 0, Encoding.UTF8.GetByteCount(OldPass));
                OldPass = Convert.ToBase64String(bytesOldPass);
            }


            if ((utilizador.PalavraPass != null && OldPass != null))
            {
                if (edit.PalavraPass != OldPass)
                    ModelState.AddModelError("OldPass", "Password incorreta!");
            }

            if ((utilizador.PalavraPass == null && OldPass != null) || (utilizador.PalavraPass != null && OldPass == null))
            {
                ModelState.AddModelError("OldPass", "Tem que preencher ambos os campos se deseja mudar a Password");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var file = colletion.Files.First();
                    if (file.ContentType != null)
                    {
                        string caminho = Path.Combine(_hostEnvironment.ContentRootPath, "wwwroot\\img\\Fotos");
                        string nome_ficheiro = Path.GetFileName(file.FileName);
                        string caminho_completo = Path.Combine(caminho, nome_ficheiro);
                        FileStream fs = new FileStream(caminho_completo, FileMode.Create);
                        file.CopyTo(fs);
                        fs.Close();


                        string caminho_deleteC = Path.Combine(caminho, edit.Fotografica);


                        System.IO.File.Delete(caminho_deleteC);

                        edit.Fotografica = nome_ficheiro;
                    }

                    edit.NumTelefone = utilizador.NumTelefone;

                    if (utilizador.PalavraPass != null)
                        edit.PalavraPass = utilizador.PalavraPass;

                    _context.Update(edit);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("IndexPerfil");
                }
                catch (Exception)
                {
                    edit.NumTelefone = utilizador.NumTelefone;

                    if (utilizador.PalavraPass != null)
                        edit.PalavraPass = utilizador.PalavraPass;

                    _context.Update(edit);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("IndexPerfil");
                }
            }
            var utl = _context.Utilizador.FirstOrDefault(x => x.IdUtilizador == Convert.ToInt32(HttpContext.Session.GetInt32("UserId")));
            return View(utl);
        }
        //########################################

        //#############Planos###################
        public async Task<IActionResult> IndexPlanos()
        {
            var id = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
            var prof = _context.Professor.FirstOrDefault(x => x.IdUtilizador == id);
            var weWonderGymDataBaseContext = _context.PlanoExercicio.Where(x => x.IdProfessor == prof.IdProfessor).Include(p => p.IdSocioNavigation.IdUtilizadorNavigation).Where(x => x.IdSocioNavigation.IdUtilizadorNavigation.Estado == 1);
            return View(await weWonderGymDataBaseContext.ToListAsync());
        }

        public IActionResult CreatePlano()
        {
            ViewData["IdSocio"] = _context.Socio.Include(x => x.IdUtilizadorNavigation).Where(x => x.IdUtilizadorNavigation.Estado == 1).Select(a =>
                           new SelectListItem
                           {
                               Value = a.IdSocio.ToString(),
                               Text = a.IdUtilizadorNavigation.Email,
                           }).ToList();

            return View();
        }

        // POST: PlanoExercicios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePlano([Bind("IdPlano,IdProfessor,IdSocio,Descricao,Ativo")] PlanoExercicio planoExercicio)
        {
            if (ModelState.IsValid)
            {

                int utlId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                var prof = _context.Professor.FirstOrDefault(x => x.IdUtilizador == utlId);


                planoExercicio.IdProfessorNavigation = prof;
                planoExercicio.IdProfessor = prof.IdProfessor;
                planoExercicio.Ativo = true;
                _context.Add(planoExercicio);
                await _context.SaveChangesAsync();
                return RedirectToAction("IndexPlanos");
            }
            ViewData["IdProfessor"] = new SelectList(_context.Professor, "IdProfessor", "Especialidade", planoExercicio.IdProfessor);
            ViewData["IdSocio"] = new SelectList(_context.Socio, "IdSocio", "Altura", planoExercicio.IdSocio);
            return View(planoExercicio);
        }

        public IActionResult CreateInstExercicio(int idPlano)
        {
            ViewData["IdExercicio"] = new SelectList(_context.ExercicioGinasio, "IdExercicio", "Nome");
            return View();
        }

        // POST: ExercicoPlanoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateInstExercicio(int idPlano, [Bind("IdExercicio,IdPlano,DuracaoPeriodoDescanso,QuantidadeSeries,NumeroRepeticoes,DuracaoExercicios,Ordem")] ExercicoPlano exercicoPlano)
        {
            var ordem = _context.ExercicoPlano.FirstOrDefault(x => x.Ordem == exercicoPlano.Ordem && x.IdPlano == exercicoPlano.IdPlano);



            if (ordem != null)
            {
                ModelState.AddModelError("Erro", "Não pode ter dois exercicios com a mesma ordem!");
                ViewBag.Sucess = "erro";

            }


            if (ModelState.IsValid)
            {
                exercicoPlano.IdPlanoNavigation = _context.PlanoExercicio.FirstOrDefault(x => x.IdPlano == idPlano);
                exercicoPlano.IdPlano = idPlano;
                _context.Add(exercicoPlano);
                await _context.SaveChangesAsync();
                ViewBag.Sucess = "sucesso";
                ViewData["IdExercicio"] = new SelectList(_context.ExercicioGinasio, "IdExercicio", "Descricao", exercicoPlano.IdExercicio);
                return PartialView(exercicoPlano);
            }
            ViewData["IdExercicio"] = new SelectList(_context.ExercicioGinasio, "IdExercicio", "Descricao", exercicoPlano.IdExercicio);
            ViewData["IdPlano"] = new SelectList(_context.PlanoExercicio, "IdPlano", "Descricao", exercicoPlano.IdPlano);
            return PartialView(exercicoPlano);
        }

        public async Task<IActionResult> ListExercicios(int id)
        {
            var weWonderGymDataBaseContext = _context.ExercicoPlano.Include(e => e.IdExercicioNavigation).Include(e => e.IdPlanoNavigation).Where(x => x.IdPlano == id);
            return View(await weWonderGymDataBaseContext.OrderBy(x => x.Ordem).ToListAsync());
        }

        public IActionResult EliminarExercicios(int? id)
        {
            var remove = _context.ExercicoPlano.FirstOrDefault(x => x.IdExercicio == id);
            _context.ExercicoPlano.Remove(remove);
            _context.SaveChanges();

            return PartialView("ListPartialExercicios", _context.ExercicoPlano.Include(e => e.IdExercicioNavigation).Include(e => e.IdPlanoNavigation).OrderBy(x => x.Ordem));
        }


        public async Task<IActionResult> EditExercicos(int? id)
        {
            ExercicoPlano edit = _context.ExercicoPlano.FirstOrDefault(x => x.IdExercicio == id);

            if (id == null)
            {

WeWonderGym/WeWonderGym/Views/Professores/CreatePeso.cshtml
@model WeWonderGym.Models.Peso


<div class="row">
    <div class="col-md-4">
        <form asp-action="CreatePeso">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Adicionar Pesagem" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

WeWonderGym/WeWonderGym/Views/Professores/EditPerfil.cshtml
@model WeWonderGym.Models.Utilizador
@{
    ViewData["Title"] = "EditPerfil";
}

<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="~/img/elements/fav.png">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Adicionar Professor</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="/stylesheet" href="~/css/linearicons.css">
    <link rel="stylesheet" href="~/css/owl.carousel.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/nice-select.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/main.css">
</head>
<body>
    <div class="main-wrapper">

        <!-- Start offer Area -->
        <section class="offer-area pt-100" id="offer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <a asp-controller="Professores" asp-action="VerPefil">
                            <div class="single-offer">
                                <img class="img-fluid" src="~/img/o1.png" alt="">
                                <h4>Ver Perfil</h4>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4">
                        <a asp-controller="Professores" asp-action="Edit">
                            <div class="single-offer">
                                <img class="img-fluid" src="~/img/o2.png" alt="">
                                <h4>Alterar dados pessoais</h4>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4">
                        <a asp-controller="Professores" asp-action="AlterarFoto">
                            <div class="single-offer">
                                <img class="img-fluid" src="~/img/o3.png" alt="">
                                <h4>Alterar foto de perfil</h4>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </section>
        <!-- End offer Area -->
        <!-- Start Generic Area -->
        <section class="about-generic-area section-gap">
            <div style="padding-left:15%;padding-right:15%;">
                <form asp-action="EditPerfil" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="Fotografica" class="control-label"></label>
                        <input asp-for="Fotografica" type="file" value="@ViewBag.Fotografica" accept="image/*" class="form-control" />
                        <span asp-validation-for="Fotografica" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="NumTelefone" class="control-label"></label>
                        <input asp-for="NumTelefone" class="form-control" value="@ViewBag.NumTelefone" required />
                        <span asp-validation-for="NumTelefone" class="text-danger"></span>
                    </div>
                    <h3>Redefenir Password</h3>
                    <p><font color="red">@Html.ValidationMessage("OldPass")</font></p>
                    <div class="form-group">
                        <label class="control-label">Password Antiga</label>
                        <input class="form-control" type="password" name="OldPass" required />
                        <span asp-validation-for="PalavraPass" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="PalavraPass" class="control-label">Nova Password</label>
                        <input asp-for="PalavraPass" class="form-control" type="password" required />
                        <span asp-validation-for="PalavraPass" class="text-danger"></span>
                    </div>

                    <div>
                        <input type="submit" value=" Adicionar" class="primary-btn" />
                    </div>
                </form>
            </div>
        </section>
    </div>

    <div class="modal" id="modal">
    </div>

    <!-- End Generic Start -->
    <script src="~/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="~/js/vendor/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
    <script src="~/js/easing.min.js"></script>
    <script src="~/js/hoverIntent.js"></script>
    <script src="~/js/superfish.min.js"></script>
    <script src="~/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.sticky.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/parallax.min.js"></script>
    <script src="~/js/waypoints.min.js"></script>
    <script src="~/js/jquery.counterup.min.js"></script>
    <script src="~/js/mail-script.js"></script>
    <script src="~/js/main.js"></script>
</body>
</html>

<script>
    $(function () {
        $("#mensagens").click(function () {
            $("#modal").load("Utilizadores/MenssagensIndex", function () {
                $("#modal").modal();
            })
        });
    })
</script>

WeWonderGym/WeWonderGym/Views/Professores/IndexPlanos.cshtml
@model IEnumerable<WeWonderGym.Models.PlanoExercicio>

<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="~/img/elements/fav.png">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Adicionar Professor</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="stylesheet" href="~/css/linearicons.css">
    <link rel="stylesheet" href="~/css/owl.carousel.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/nice-select.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/main.css">
</head>
<body>
    <div class="main-wrapper">
        <section class="generic-banner relative">
            <div class="container">
                <div class="row height align-items-center justify-content-center" style="max-height:500px">
                    <div class="col-lg-10">
                        <div class="generic-banner-content">
                            <h2 class="text-white">Planos de Treino</h2>
                            <p class="text-white">Pode aqui visualizar e criar planos  <br> e os sócios correspondentes.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- End offer Area -->
        <!-- Start Generic Area -->
        <section class="schedule-area section-gap" style="padding-left:1%">
            <a class="genric-btn primary e-large" style="color:#ffffff" id="criar">Criar Plano</a>
            <div class="table-wrap col-lg-12">
                <table class="schdule-table table table-bordered">
                    <thead class="thead-light">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Descricao)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Ativo)
                            </th>
                            <th>
                                Socio
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Descricao)
                                </td>
                                <td>
                                    @if (item.Ativo == true)
                                    {
                                        <span> Ativo </span>
                                    }
                                    else
                                    {
                                        <span> Inativo </span>
                                    }
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IdSocioNavigation.IdUtilizadorNavigation.Nome)
                                </td>
                                <td>
                                    <a style="color:#ffffff" id="Exercicio" class="genric-btn primary small exercicio" data-id="@item.IdPlano">Exercicios</a>
                                    <a style="color:#ffffff" id="Adicionar" class="genric-btn primary small adicionar" data-id="@item.IdPlano">Adicionar Exercício</a>
                                    @if (item.Ativo == true)
                                    {
                                        <a style="color:#ffffff" id="Desativar" class="genric-btn primary small ativar" data-id="@item.IdPlano" asp-controller="Professores" asp-action="EditEstadoPlano" asp-route-id="@item.IdPlano">Desativar Plano</a>
                                    }
                                    else
                                    {
                                        <a style="color:#ffffff" id="Ativar" class="genric-btn primary small desativar" data-id="@item.IdPlano"asp-controller="Professores" asp-action="EditEstadoPlano"     asp-route-id="@item.IdPlano">Ativar Plano</a>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </section>
    </div>

    <div class="modal" id="modal">

    </div>
    <script src="~/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="~/js/vendor/bootstrap.min.js"></script>
    <script src="~/js/easing.min.js"></script>
    <script src="~/js/hoverIntent.js"></script>
    <script src="~/js/superfish.min.js"></script>
    <script src="~/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.sticky.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/jquery.counterup.min.js"></script>
    <script src="~/js/main.js"></script>
</body>
</html>

@section scripts{
    <script>
        $(function () {
            $("#criar").click(function () {
                $("#modal").load("CreatePlano", function () {
                    $("#modal").modal();
                })
            });
        })

        $(function () {
            $(".exercicio").click(function () {
                var id = $(this).attr("data-id");
                $("#modal").load("ListExercicios?id=" + id, function () {
                    $("#modal").modal();
                })
            });
        })

        $(function () {
            $(".adicionar").click(function () {
                var id = $(this).attr("data-id");
                $("#modal").load("CreateInstExercicio?idPlano=" + id, function () {
                    $("#modal").modal();
                })
            });
        })

        $(function () {
            $(".editar").click(function () {
                var id = $(this).attr("data-id");
                $("#modal").load("EditExercicos?id=" + id, function () {
                    $("#modal").modal();
                })
            });
        })




    </script>
    <script>
        $(function () {
            $("#mensagens").click(function () {
                $("#modal").load("Utilizadores/MenssagensIndex", function () {
                    $("#modal").modal();
                })
            });
        })
    </script>

}

WeWonderGym/WeWonderGym/Views/Professores/IndexSociosPT.cshtml
@{
    ViewData["Title"] = "IndexSociosPT";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="~/img/elements/fav.png">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Ginasio</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="/stylesheet" href="~/css/linearicons.css">
    <link rel="stylesheet" href="~/css/owl.carousel.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/nice-select.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/main.css">
</head>
<body>
    <section class="banner-aulas relative" id="home" style="max-height:500px;">
        <div class="container">
            <div class="row fullscreen d-flex align-items-start justify-content-start" style="padding-top:12.5%; max-height:500px;">
                <div class="banner-content col-lg-12 col-md-12">
                    <h2 class="text-white">Personal Trainer</h2>
                    <p class="text-white">Pode aqui visualizar os socios do qual é Personal Trainer</p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->
    <!-- About Generic Start -->
    <div class="main-wrapper">
        <!-- Start offer Area -->
        <section class="offer-area pt-100" id="offer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4" style="left:15%">
                        <a asp-controller="Professores" asp-action="ListSociosPT">
                            <div class="single-offer">
                                <img class="img-fluid" src="~/img/o1.png" alt="">
                                <h4>Sócios de qual é Personal Trainer</h4>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4" style="left:20%">
                        <a asp-controller="Professores" asp-action="Pesagem">
                            <div class="single-offer">
                                <img class="img-fluid" src="~/img/o2.png" alt="">
                                <h4>Pesagem</h4>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <!-- End offer Area -->
    <!-- Start Generic Area -->
    <section class="about-generic-area section-gap">
    </section>

    <div class="modal" id="modal">

    </div>
    <script src="~/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="~/js/vendor/bootstrap.min.js"></script>
    <script src="~/js/easing.min.js"></script>
    <script src="~/js/hoverIntent.js"></script>
    <script src="~/js/superfish.min.js"></script>
    <script src="~/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.sticky.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/jquery.counterup.min.js"></script>
    <script src="~/js/main.js"></script>
</body>


<script>
    $(function () {
        $("#mensagens").click(function () {
            $("#modal").load("Utilizadores/MenssagensIndex", function () {
                $("#modal").modal();
            })
        });
    })
</script>

WeWonderGym/WeWonderGym/Views/Professores/ListExercicios.cshtml
@model IEnumerable<WeWonderGym.Models.ExercicoPlano>
@{
    Layout = null;
}
<head>
    <link rel="stylesheet" href="~/css/bootstrap.css">
</head>

<div  class="modal-dialog" style="padding-top:15%; max-width:100%; max-height:100%;">
    <div id="troca" class="modal-content" style="padding-top:2%;padding-bottom:2%;padding-left:2%;padding-right:2%;">
        <partial name="ListPartialExercicios" model="Model" />
    </div>
</div><!-- /.modal-dialog -->

WeWonderGym/WeWonderGym/Views/Professores/ListPartialExercicios.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<WeWonderGym.Models.ExercicoPlano>

<table class="table" id="tabela">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ordem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdExercicioNavigation.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QuantidadeSeries)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroRepeticoes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DuracaoExercicios)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DuracaoPeriodoDescanso)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ordem)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdExercicioNavigation.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.QuantidadeSeries)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumeroRepeticoes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DuracaoExercicios)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DuracaoPeriodoDescanso)
                </td>
                <td>
                    <a asp-controller="Professores" asp-action="EliminarExercicios" asp-route-id="@item.IdExercicio" style="color:#ffffff" class="genric-btn primary small adicionar"
                       data-ajax="true"
                       data-ajax-method="GET"
                       data-ajax-mode="replace"
                       data-ajax-update="#tabela"
                       data-ajax-confirm="Tem a certeza que quer eliminar este exercicio?">Eliminar</a>
                    <a style="color:#ffffff" id="editar" class="genric-btn primary small editar" data-id="@item.IdExercicio" asp-controller="Professores" asp-action="EditExercicos" asp-route-id="@item.IdExercicio"
                       data-ajax="true"
                       data-ajax-method="GET"
                       data-ajax-mode="replace"
                       data-ajax-update="#troca"
                       >Editar</a>
                </td>

            </tr>
        }
    </tbody>
</table>